---
- name: CORE - Update installed packages
  apt:
    update_cache: yes
    upgrade: safe
  become: true
  ignore_errors: true

- name: CORE - Install basic packages
  apt:
    name: "{{ system_packages }}"
    state: present
  become: true

- name: CORE - Change hostname
  hostname:
    name: "{{ new_hostname }}"
    use: systemd
  become: true

- name: CORE - Set correct timezone
  timezone:
    name: "{{ tz }}"
  become: true

- name: CORE - Ensure locale exists
  locale_gen:
    name: "{{ locale }}.UTF-8"
    state: present
  become: true

- name: CORE - NetworkManager - Add wifi configuration
  template:
    src: wifi.j2
    dest: "/etc/NetworkManager/system-connections/{{ item }}"
    owner: root
    group: root
    mode: '0600'
  with_items: "{{ wifi_networks }}"
  become: true
  register: network_conf
  
- name: CORE - NetworkManager - Restart the service
  systemd:
    name: NetworkManager
    state: restarted
    enabled: yes
  become: true
  when: network_conf.changed

- name: CORE - Change root password
  user:
    name: root
    password: "{{ new_root_password | password_hash('sha512') }}"
    update_password: always
  become: true
  changed_when: false
  when: new_root_password is defined
 
- name: CORE - New user
  block:
    - name: CORE - Add new user
      user:
        name: "{{ new_user_name }}"
        password: "{{ new_user_pass | password_hash('sha512') }}"
        update_password: on_create
        shell: /bin/zsh
        groups: cosmo,sudo,audio,video,input,aid_system,aid_graphics,aid_input,aid_audio,aid_net_bt_admin,aid_net_bt,aid_inet,aid_net_raw,aid_net_admin
        create_home: true
        home: "/home/{{ new_user_name }}"
        state: present
      become: true
      register: new_user
    - name: CORE - Allow passwordless sudo for new user
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: "^{{ new_user_name }} ALL="
        line: "{{ new_user_name }} ALL=(ALL) NOPASSWD:ALL"
        validate: '/usr/sbin/visudo -cf %s'
      become: true
    - name: CORE - Copy default .config from cosmo to the new user
      copy:
        src: "/home/cosmo/.config"
        dest: "/home/{{ new_user_name }}"
        owner: "{{ new_user_name }}"
        group: "{{ new_user_name }}"
        remote_src: yes
      become: true
      ignore_errors: true
    - name: CORE - Force disconnect logged user in GUI
      systemd:
        name: display-manager
        state: restarted
      become: true
      when: new_user.changed
  when: new_user_name is defined and new_user_pass is defined

- name: CORE - Purge default user
  block:
    - name: CORE - Change active SSH user
      set_fact:
        ansible_ssh_user: "{{ new_user_name }}"
        ansible_ssh_pass: "{{ new_user_pass }}"
    - name: CORE - Delete default user cosmo
      user:
        name: cosmo
        state: absent
        remove: yes
        force: yes
      become: true
  when: new_user.changed


