---
- name: COSMO - Keyboard layout
  block:
    - name: COSMO - Check if .profile file exist
      stat:
        path: "/home/{{ ansible_ssh_user }}/.profile"
      register: profile
    - name: COSMO - Create .profile
      file:
        path: "/home/{{ ansible_ssh_user }}/.profile"
        state: touch
      when: not profile.stat.exists
    - name: COSMO - Add .profile template to correct keyboard layout
      lineinfile:
        path: "/home/{{ ansible_ssh_user }}/.profile"
        state: present
        regexp: "^/usr/bin/setxkbmapsetxkbmap"
        line: "/usr/bin/setxkbmap -model planetcosmo -layout {{ cosmo_keyboard_layout }}"
      become: true

- name: COSMO - MicroSD
  block:
    - name: COSMO - Create microSD mount point
      file:
        path: /media/sdcard
        state: directory
        owner: root
        group: root
        mode: 0777
      become: true
    - name: COSMO - Create microSD mount point symlink in user directory
      file:
        src: /media/sdcard
        dest: "/home/{{ ansible_ssh_user }}/sdcard"
        owner: root
        group: root
        state: link
      become: true
    - name: COSMO - Retrieve microSD UUID
      shell: blkid | grep mmcblk1p1 | awk '{print $4}' | grep -Po '(?<=UUID=).*' | tr -d '"'
      register: sd_uuid
      changed_when: false
      become: true
    - name: COSMO - Retrieve microSD format
      shell: blkid | grep mmcblk1p1 | awk '{print $5}' | grep -Po '(?<=TYPE=).*' | tr -d '"'
      register: sd_format
      changed_when: false
      become: true
    - name: COSMO - Mount microSD
      mount:
        path: /media/sdcard
        src: "UUID={{ sd_uuid.stdout }}"
        fstype: "{{ sd_format.stdout }}" 
        opts: user,fmask=0111,dmask=0000
        state: present
      become: true

- name: COSMO - Touchscreen xorg mtrack (relative positioning)
  block:
    - name: COSMO - Touchscreen xorg mtrack - Add conf file
      copy:
        src: "common/50-mtrack.conf"
        dest: "/usr/share/X11/xorg.conf.d/50-mtrack.conf"
        owner: "root"
        group: "root"
        mode: '0644'
      become: true
      when: touch_relative is true
      notify: Restart display-manager
    - name: COSMO - Touchscreen xorg mtrack - Disable and stop cosmo-rightclick service
      systemd:
        name: rightclick
        enabled: no
        state: stopped
      become: true
      notify: Restart display-manager
      ignore_errors: true
  when: touch_relative is true

- name: COSMO - Touchscreen xorg evdev (absolute positioning)
  block:
    - name: COSMO - Touchscreen xorg evdev - Get cosmo-rightclick
      git:
        repo: https://github.com/m600x/cosmo-rightclick.git
        dest: "/home/{{ ansible_ssh_user }}/cosmo-rightclick"
        clone: yes
        update: yes
    - name: COSMO - Touchscreen xorg evdev - Build cosmo-rightclick
      make:
        chdir: "/home/{{ ansible_ssh_user }}/cosmo-rightclick"
        target: all
    - name: COSMO - Touchscreen xorg evdev - Move binary to /usr/local/bin/cosmo-rightclick
      copy:
        src: "/home/{{ ansible_ssh_user }}/cosmo-rightclick/out/cosmo-rightclick"
        dest: "/usr/local/bin/cosmo-rightclick"
        owner: root
        group: root
        mode: '0755'
        remote_src: yes
      become: true
    - name: COSMO - Touchscreen xorg evdev - Add cosmo-rightclick service
      template:
        src: rightclick_service.j2
        dest: "/etc/systemd/system/rightclick.service"
        owner: root
        group: root
        mode: '0755'
      become: true
      notify: Restart display-manager
    - name: COSMO - Touchscreen xorg evdev - Enable and start cosmo-rightclick service
      systemd:
        name: rightclick
        enabled: yes
      become: true
      notify: Restart display-manager
    - name: COSMO - Touchscreen xorg evdev - Ensure mtrack conf is absent
      file:
        path: "/usr/share/X11/xorg.conf.d/50-mtrack.conf"
        state: absent
      become: true
      notify: Restart display-manager
  when: touch_rightclick is true and touch_relative is false

- name: COSMO - Touchscreen xorg evdev default
  block:
    - name: COSMO - Touchscreen xorg default - Disable and stop cosmo-rightclick service
      systemd:
        name: rightclick
        enabled: no
        state: stopped
      become: true
      notify: Restart display-manager
      ignore_errors: true
    - name: COSMO - Touchscreen xorg default - Ensure mtrack conf is absent
      file:
        path: "/usr/share/X11/xorg.conf.d/50-mtrack.conf"
        state: absent
      become: true
      notify: Restart display-manager
  when: touch_rightclick is false and touch_relative is false

- name: COSMO - Touchscreen xorg mtrack and evdev conf template
  template:
    src: 10-evdev.j2
    dest: "/usr/share/X11/xorg.conf.d/10-evdev.conf"
    owner: root
    group: root
    mode: '0644'
  become: true
  notify: Restart display-manager

- name: COSMO - Keyboard
  block:
    - name: COSMO - Keyboard - Add general hotkey binding
      lineinfile:
        path: "/home/{{ ansible_ssh_user }}/.config/kglobalshortcutsrc"
        regexp: "^{{ item.split('=').0 }}"
        line: "{{ item }}"
        state: present
      with_items: "{{ kde_shortcuts }}"
      notify: Restart display-manager
    - name: COSMO - Keyboard - Add kb-backlight script control
      copy:
        src: common/kb-backlight.sh
        dest: "/usr/local/bin/kb-backlight"
        owner: root
        group: root
        mode: '0755'
      become: true
    - name: COSMO - Keyboard - Add backlight hotkey binding
      lineinfile:
        path: "/home/{{ ansible_ssh_user }}/.config/kglobalshortcutsrc"
        line: "{{ item }}"
        insertafter: '^\[khotkeys\]'
        state: present
      with_items: "{{ kb_backlight_shortcuts }}"

      notify: Restart display-manager
    - name: COSMO - Keyboard - Add backlight hotkey definition
      blockinfile:
        path: "/home/{{ ansible_ssh_user }}/.config/khotkeysrc"
        insertbefore: "[Gestures]"
        block: "{{ lookup('file', '../files/common/khotkey') }}"
      notify: Restart display-manager
