---
- include_tasks: core.yml

- include_tasks: cosmo.yml

- include_tasks: custom.yml

- include_tasks: ssh.yml
  when: ssh_support

- include_tasks: mobile.yml
  when: mobile_data_support

- include_tasks: vpn.yml
  when: vpn_support

- include_tasks: vnc.yml
  when: vnc_support

- include_tasks: specific.yml
  when: run_specific
