---
- name: Vault CLI
  block:
    - name: Vault - Check if vault cli is already installed
      stat:
        path: /usr/local/bin/vault
      register: vault_installed
    - name: Vault - Download and install Vault CLI
      unarchive:
        src: https://releases.hashicorp.com/vault/1.6.0/vault_1.6.0_linux_arm64.zip
        dest: /usr/local/bin
        remote_src: yes
      become: true
      when: not vault_installed.stat.exists

- name: Ansible
  block:
    - name: Ansible - Add ansible repo
      apt_repository:
        repo: deb http://ppa.launchpad.net/ansible/ansible/ubuntu trusty main
        state: present
    - name: Ansible - Add ansible repo key
      apt_key:
        keyserver: keyserver.ubuntu.com
        id: 93C4A3FD7BB9C367
    - name: Ansible - Install ansible
      apt:
        name: ansible=2.9.15-1ppa~trusty
        state: present
