---
- name: SSH - Create .ssh directory if doesn't exist
  file:
    path: "/home/{{ ansible_ssh_user }}/.ssh"
    state: directory
    mode: 0700

- name: SSH - Register files to be sent
  find:
    paths: "{{ role_path }}/files/ssh"
    file_type: file
    recurse: Yes
  register: ssh_files
  delegate_to: localhost

- name: SSH - Send files
  copy:
    src: "{{ item.path }}"
    dest: "/home/{{ ansible_ssh_user }}/.ssh/{{ item.path | basename }}"
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
  with_items: "{{ ssh_files.files | flatten(levels=1) }}"

- name: SSH - Fix rights
  file:
    path: "/home/{{ ansible_ssh_user }}/.ssh/{{ item.path | basename }}"
    mode: "{{ rights[item.path | basename].rights }}"
  with_items: "{{ ssh_files.files | flatten(levels=1) }}"
  when: (item.path | basename) in rights