---
- name: VNC - Install basic packages
  apt:
    name: "{{ system_packages }}"
    state: present
  become: true

- name: VNC - Create .vnc directory if doesn't exist
  file:
    path: "/home/{{ ansible_ssh_user }}/.vnc"
    state: directory
    mode: 0755

- name: VNC - Create password for the service
  shell: "echo {{ vnc_password }} | vncpasswd -f > /home/{{ ansible_ssh_user }}/.vnc/passwd"
  changed_when: false

- name: "Change the permission to 600"
  file:
    path: "/home/{{ ansible_ssh_user }}/.vnc/passwd"
    mode: 0600

- name: VNC - Add VNC script
  template:
    src: vnc_script.j2
    dest: "/usr/local/bin/vnc"
    owner: root
    group: root
    mode: '0755'
  become: true

- name: VNC - Check if .profile file exist
  stat:
    path: "/home/{{ ansible_ssh_user }}/.profile"
  register: profile

- name: VNC - Create .profile
  file:
    path: "/home/{{ ansible_ssh_user }}/.profile"
    state: touch
  when: not profile.stat.exists

- name: VNC - Add autostart of the VNC service
  lineinfile:
    path: "/home/{{ ansible_ssh_user }}/.profile"
    state: present
    regexp: "^/usr/local/bin/vnc"
    line: "/usr/local/bin/vnc start > /dev/null 2>&1"
  become: true