---
- name: VPN - Install VPN packages
  apt:
    name: "{{ vpn_packages }}"
    state: present
    update_cache: yes
  become: true

- name: VPN - Register files to be sent
  find:
    paths: "{{ role_path }}/files/vpn"
    file_type: file
    hidden: no
    recurse: Yes
  register: vpn_files
  delegate_to: localhost

- name: VPN - Extract VPN conf to /etc/openvpn/client
  unarchive:
    src: "{{ item.path }}"
    dest: /etc/openvpn/client
  with_items: "{{ vpn_files.files | flatten(levels=1) }}"
  become: true
  changed_when: false

- name: VPN - Change chown of conf files
  file:
    path: /etc/openvpn/client
    owner: root
    group: root
    mode: '0755'
    recurse: yes
  become: true
  changed_when: false

- name: VPN - Add VPN script
  template:
    src: vpn_script.j2
    dest: "/usr/local/bin/vpn"
    owner: root
    group: root
    mode: '0755'
  become: true