---
- name: Setting vars
  hosts: all
  gather_facts: false
  tasks:
    - set_fact:
        ansible_host: '127.0.0.1'
        new_hostname: 'cosmo'
        new_user_name: '__MUST_CHANGE__'
        new_user_pass: '__MUST_CHANGE__'
        new_root_password: '__MUST_CHANGE__'
        cosmo_keyboard_layout: 'gb'
        locale: 'en_US'
        tz: 'Europe/Paris'
        relative_touchscreen: true
        # SSH support
        ssh_support: false
        # LTE support
        mobile_data_support: true
        mobile_data_roaming: false
        mobile_data_settings:
          AccessPointName: orange.fr
          Username: orange
          Password: orange
          AuthenticationMethod: pap
        # VPN support
        vpn_support: false
        # VNC support
        vnc_support: false
        vnc_password: '__MUST_CHANGE__'
        vnc_port: 5900

- name: Check which user to be for SSH
  hosts: all
  gather_facts: false
  tasks:
    - name: Set credentials with default cosmo:cosmo
      set_fact:
        ansible_ssh_user: 'cosmo'
        ansible_ssh_pass: 'cosmo'
    - name: Test SSH connection
      ping:
      ignore_unreachable: true
      ignore_errors: true
      changed_when: false
      register: ssh_test
    - name: "Fall back to user {{ new_user_name }}, default user {{ ansible_ssh_user }} appear to be missing"
      set_fact:
        ansible_ssh_user: "{{ new_user_name }}"
        ansible_ssh_pass: "{{ new_user_pass }}"
      when: ssh_test.unreachable is defined
- name: Check which root password is correct
  hosts: all
  gather_facts: false
  tasks:
    - name: Set sudo password with default value cosmo
      set_fact:
        ansible_sudo_pass: 'cosmo'
    - name: Test default root password
      command: echo "sudo password correct"
      ignore_errors: true
      changed_when: false
      register: root_test
      become: true
    - name: "Change root password with new value"
      set_fact:
        ansible_sudo_pass: "{{ new_root_password }}"
      when: root_test.failed
    - set_fact:
        ansible_ssh_user: "{{ new_user_name }}"
        ansible_ssh_pass: "{{ new_user_pass }}"
        ansible_sudo_pass: "{{ new_root_password }}"

- name: Cosmo installation
  hosts: all
  roles:
    - cosmo-installation
