---
- name: Cosmo | Bootstrap connexion
  hosts: planet_computers
  gather_facts: false

  tasks:
    - name: Bootstrap connexion
      import_tasks: tasks/bootstrap.yml
      when: bootstrapped is undefined

    - name: Mark cosmo as bootstrapped
      set_fact:
        bootstrapped: true

- name: Cosmo | Custom
  hosts: planet_computers
  become: true
  diff: true

  tasks:
    - name: Cosmo | Custom - Install Oh-My-ZSH
      shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
      become_user: "{{ ansible_ssh_user }}"
      ignore_errors: true
      changed_when: false
