---
- name: Cosmo | Bootstrap connexion
  hosts: planet_computers
  gather_facts: false

  tasks:
    - name: Bootstrap connexion
      import_tasks: tasks/bootstrap.yml
      when: bootstrapped is undefined

    - name: Mark cosmo as bootstrapped
      set_fact:
        bootstrapped: true

- name: Cosmo | Users
  hosts: planet_computers
  become: true
  diff: true

  tasks:
    - name: Cosmo | Users - Change root password
      user:
        name: root
        password: "{{ new_root_password | password_hash('sha512') }}"
        update_password: always
      changed_when: false
      when: new_root_password is defined

    - name: Cosmo | Users - Add new user
      user:
        name: "{{ new_user_name }}"
        password: "{{ new_user_password | password_hash('sha512') }}"
        update_password: always
        shell: /bin/zsh
        groups: cosmo,sudo,audio,video,input,aid_system,aid_graphics,aid_input,aid_audio,aid_net_bt_admin,aid_net_bt,aid_inet,aid_net_raw,aid_net_admin
        create_home: true
        home: "/home/{{ new_user_name }}"
        state: present
      register: new_user
      when: ansible_ssh_user == 'cosmo' and new_user_name is defined and new_user_password is defined

    - name: Cosmo | Users - New user
      block:
        - name: Cosmo | Users - Allow passwordless sudo for new user
          lineinfile:
            path: /etc/sudoers
            state: present
            regexp: "^{{ new_user_name }} ALL="
            line: "{{ new_user_name }} ALL=(ALL) NOPASSWD:ALL"
            validate: '/usr/sbin/visudo -cf %s'

        - name: Cosmo | Users - Copy default .config from cosmo to the new user
          copy:
            src: "/home/cosmo/.config"
            dest: "/home/{{ new_user_name }}"
            owner: "{{ new_user_name }}"
            group: "{{ new_user_name }}"
            remote_src: yes
          ignore_errors: true

        - name: Cosmo | Users - Force disconnect logged user in GUI
          systemd:
            name: display-manager
            state: restarted

        - name: Cosmo | Users - Change active SSH user
          set_fact:
            ansible_ssh_user: "{{ new_user_name }}"
            ansible_ssh_pass: "{{ new_user_password }}"

        - name: Cosmo | Users - Delete default user cosmo
          user:
            name: cosmo
            state: absent
            remove: yes
            force: yes
      when: new_user is defined and new_user.changed